# Generated by Django 4.1.2 on 2022-11-07 17:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-Я]+$')], verbose_name='Тип животного')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-Я]+$')], verbose_name='Кличка')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('height', models.FloatField(verbose_name='Рост')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('passport', models.BooleanField(verbose_name='Наличие паспорта')),
                ('pass_num', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')], verbose_name='Номер паспорта')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type', verbose_name='Тип животного')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
